apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "gungnir-operator.fullname" . }}
  labels:
    {{- include "gungnir-operator.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "gungnir-operator.serviceAccountName" . }}
    namespace: {{ include "gungnir-operator.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "gungnir-operator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
