{{- if .Values.leaderElection.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "gungnir-operator.fullname" . }}-leader-election
  namespace: {{ include "gungnir-operator.namespace" . }}
  labels:
    {{- include "gungnir-operator.labels" . | nindent 4 }}
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
{{- end }}
