{{- if .Values.leaderElection.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "gungnir-operator.fullname" . }}-leader-election
  namespace: {{ include "gungnir-operator.namespace" . }}
  labels:
    {{- include "gungnir-operator.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "gungnir-operator.serviceAccountName" . }}
    namespace: {{ include "gungnir-operator.namespace" . }}
roleRef:
  kind: Role
  name: {{ include "gungnir-operator.fullname" . }}-leader-election
  apiGroup: rbac.authorization.k8s.io
{{- end }}
